### ISSUE TITLE
Would you be open to a PR that extracts the "shell" code from default.nix/shell.nix?

### ISSUE THREAD

**Issue by SRGOM** [toraritte/shell.nixes#1]
Hello, first off, thank you for very well written and well commented code. I'm using this in my own project and rather than duplicating and diverging, I want to upstream my own changes. To that effect, would you be open to a PR that extracts the shell code from shell.nix into a `.sh` file of it's own. I'm pretty sure you already know but one can also say `shellHook = ./shellHookCode.sh;`. 

I'd like to separate out the postgres part.

**Comment by toraritte** [comment]
First of all, I apologize for the very late reply - I missed your message simply because not used to receiving PRs or issues opened to my own repos...

> I'm pretty sure you already know but one can also say `shellHook = ./shellHookCode.sh;`.

Thanks! This should have been straightforward, but didn't put two and two together. The reason most of my code is profusely commented is because I have a lot going on and most of the things Nix does still seems magical (and can't keep most of the stuff in my head).

Please submit PR whenever you are ready - or this repo could also be "opened up" so that one can contribute directly. Hell, it can be even moved out to somewhere more appropriate if people find it useful.

Thank you again!

**Comment by toraritte** [comment]
Started working on this in 0dc36fdc583ffaeb6b6fcc9a048709549a32c9b0, and I think all the kinks have been worked out by the time getting to 7fc7059fda4ce33c19395b3fae38ba8ef8f209fd.

Noting here that `shellHook = ./shellHookCode.sh;` didn't work, and had to use [`builtins.readFile`](https://nixos.org/manual/nix/stable/language/builtins.html#builtins-readFile) (and some other [Nix builtins](https://nixos.org/manual/nix/stable/language/builtins.html) at times).

Thanks again!
